/**
 * Experience area options loaded from the job-specializations CSV.
 * These are the specialization names from the Tech Fleet training framework.
 * Used in profile and general application forms.
 */
export const EXPERIENCE_AREAS = [
  "Accessibility Specialist",
  "AI User Experience",
  "Back-end Developer",
  "Branding",
  "Business Analysis",
  "Client Success",
  "Community Building & Engagement",
  "Content Strategy",
  "Cross-Functional Collaboration",
  "Customer Research",
  "Cybersecurity",
  "Data Analytics",
  "Data Engineering",
  "Data Science",
  "Database Development",
  "DevOps",
  "Digital Marketing",
  "Event Planning",
  "Facilitation",
  "Front-end Developer",
  "Full-stack Developer",
  "Graphic Design",
  "Growth Marketing",
  "Human Resources",
  "Illustration",
  "Information Architecture",
  "Innovation & Strategy",
  "Machine Learning",
  "Marketing Analytics",
  "Meeting Coordination",
  "Mentorship",
  "Mobile Development",
  "Motion Design",
  "People Operations",
  "Product Design",
  "Product Management",
  "Product Marketing",
  "Product Operations",
  "Program Management",
  "Project Management",
  "Quality Assurance",
  "Scrum Master",
  "SEO Specialist",
  "Social Media Management",
  "Software Architecture",
  "Solutions Architecture",
  "Stakeholder Management",
  "Systems Administration",
  "Technical Documentation",
  "Technical Program Management",
  "UI Design",
  "User Research",
  "UX Design",
  "UX Writing",
  "Video Production",
  "Visual Design",
  "Web Development",
  "Workshop Facilitation",
  "I'm not sure yet",
] as const;

export const EDUCATION_OPTIONS = [
  "Current bootcamp student",
  "Current certification programs",
  "Current college student",
  "No formal education",
  "Previous bootcamp student",
  "Previous certification programs",
  "Previous college student",
  "Self-studied",
  "Self-Taught",
] as const;

export const PREVIOUS_ENGAGEMENT_OPTIONS = [
  "I've been on project training teams",
  "I've observed",
  "I've participated in other ways",
  "I've taken classes",
  "I've volunteered",
] as const;
