// Auto-generated from public/data/skills-framework.csv (Technical & Interpersonal Skills + Team Practices columns)
// Used as the canonical skills list across the app.

export const SKILLS_FRAMEWORK: readonly string[] = [
  "A/B Prototype Testing",
  "AI Prompting",
  "API's",
  "Acceptance Criteria Creation",
  "Accessibility",
  "Advocacy",
  "Affinity Mapping",
  "Agile Coaching",
  "Agile Method Selection",
  "Agile UX",
  "Agility",
  "Algorithm Design",
  "Assumption Formation",
  "Attention to Detail",
  "Backlog Management",
  "Behavior Driven Development (BDD) Scenarios",
  "Blockchain Programming Languages",
  "Branding",
  "Building Influence",
  "Business Acumen",
  "Buy-in Generation",
  "Click Testing",
  "Coaching",
  "Cognitive-Based Accessibility",
  "Collaboration",
  "Command Line Scripting Languages",
  "Commitment",
  "Concept Testing",
  "Conflict Resolution",
  "Contextual Inquiries",
  "Continuous Growth",
  "Creativity",
  "Critical Thinking",
  "Customer Experience Strategy",
  "Data Analysis",
  "Database Architecture",
  "Database Management",
  "Database Queries",
  "Decision-Making",
  "Delivering Feedback",
  "Design Patterns",
  "Design Systems Management",
  "Design Thinking",
  "Empowerment",
  "Epic and Feature Management",
  "Ethnography",
  "Executive Summaries",
  "Expectation Setting",
  "Experiment Design",
  "Gestalt Principles",
  "Go-to-Market Strategy",
  "Graphic Design",
  "Heuristics",
  "Icon Design",
  "Information Architecture",
  "Information Hierarchy",
  "Information Security",
  "Information Visualization",
  "Initiative",
  "Interaction Design",
  "Interviewing",
  "Kanban Board Management",
  "Logical Thinking",
  "Making Wireframes",
  "Meeting Facilitation",
  "Mental Models",
  "Motor-Based Accessibility",
  "Negotiation",
  "Network Architecture",
  "Object-oriented Programming Languages",
  "Organization",
  "Ownership",
  "Perceptual-Based Accessibility",
  "Perserverence",
  "Presentation",
  "Prioritization",
  "Problem Statements",
  "Problem-Solving",
  "Process Management",
  "Product-Market Fit",
  "Project Management",
  "Prototyping",
  "Psychological Safety",
  "Public Speaking",
  "QA Test Plan Creation",
  "Receiving Feedback",
  "Relationship Building",
  "Release Management",
  "Requirements Management",
  "Research Analysis",
  "Research Facilitation",
  "Responsive Design",
  "Scrum Management",
  "Server-Side Scripting Languages",
  "Service Design",
  "Service Leadership",
  "Signifiers",
  "Stakeholder Management",
  "Statistics",
  "Storytelling",
  "Strategic Thinking",
  "Survey Design",
  "Systems Thinking",
  "Teamwork",
  "Time Management",
  "Tree Testing",
  "Typography",
  "UI Specifications for Development",
  "UX Research Method Selection",
  "Usability Testing",
  "Use Case Scenarios",
  "User Interface Design",
  "User Stories",
  "Velocity Measurement",
  "Verbal Communication",
  "Vision Formation",
  "Visual Signifiers",
  "Web Scripting Languages",
  "Working Agreements",
  "Workshop Facilitation",
  "Written Communication"
] as const;

export const SKILLS_OPTIONS = SKILLS_FRAMEWORK.map((s) => ({ value: s, label: s }));
