/**
 * Comprehensive timezone list with display labels showing abbreviation + full name + UTC offset.
 * Format: "ABBR - Full Name (UTC ±X)"
 */
export interface TimezoneOption {
  value: string; // IANA timezone ID stored in DB
  label: string; // Display label
}

export const TIMEZONES: TimezoneOption[] = [
  { value: "Pacific/Midway", label: "SST - Samoa Standard Time (UTC -11)" },
  { value: "Pacific/Honolulu", label: "HST - Hawaii Standard Time (UTC -10)" },
  { value: "America/Anchorage", label: "AKST - Alaska Standard Time (UTC -9)" },
  { value: "America/Los_Angeles", label: "PST - Pacific Standard Time (UTC -8)" },
  { value: "America/Denver", label: "MST - Mountain Standard Time (UTC -7)" },
  { value: "America/Phoenix", label: "MST - Arizona (No DST) (UTC -7)" },
  { value: "America/Chicago", label: "CST - Central Standard Time (UTC -6)" },
  { value: "America/New_York", label: "EST - Eastern Standard Time (UTC -5)" },
  { value: "America/Indiana/Indianapolis", label: "EST - Indiana (East) (UTC -5)" },
  { value: "America/Halifax", label: "AST - Atlantic Standard Time (UTC -4)" },
  { value: "America/Caracas", label: "VET - Venezuela Time (UTC -4)" },
  { value: "America/St_Johns", label: "NST - Newfoundland Standard Time (UTC -3:30)" },
  { value: "America/Sao_Paulo", label: "BRT - Brasília Time (UTC -3)" },
  { value: "America/Argentina/Buenos_Aires", label: "ART - Argentina Time (UTC -3)" },
  { value: "Atlantic/South_Georgia", label: "GST - South Georgia Time (UTC -2)" },
  { value: "Atlantic/Azores", label: "AZOT - Azores Time (UTC -1)" },
  { value: "Atlantic/Cape_Verde", label: "CVT - Cape Verde Time (UTC -1)" },
  { value: "Europe/London", label: "GMT - Greenwich Mean Time (UTC +0)" },
  { value: "Africa/Casablanca", label: "WET - Western European Time (UTC +0)" },
  { value: "Europe/Paris", label: "CET - Central European Time (UTC +1)" },
  { value: "Europe/Berlin", label: "CET - Central European Time (UTC +1)" },
  { value: "Africa/Lagos", label: "WAT - West Africa Time (UTC +1)" },
  { value: "Europe/Athens", label: "EET - Eastern European Time (UTC +2)" },
  { value: "Africa/Cairo", label: "EET - Eastern European Time (UTC +2)" },
  { value: "Africa/Johannesburg", label: "SAST - South Africa Standard Time (UTC +2)" },
  { value: "Europe/Istanbul", label: "TRT - Turkey Time (UTC +3)" },
  { value: "Europe/Moscow", label: "MSK - Moscow Standard Time (UTC +3)" },
  { value: "Africa/Nairobi", label: "EAT - East Africa Time (UTC +3)" },
  { value: "Asia/Riyadh", label: "AST - Arabia Standard Time (UTC +3)" },
  { value: "Asia/Tehran", label: "IRST - Iran Standard Time (UTC +3:30)" },
  { value: "Asia/Dubai", label: "GST - Gulf Standard Time (UTC +4)" },
  { value: "Asia/Kabul", label: "AFT - Afghanistan Time (UTC +4:30)" },
  { value: "Asia/Karachi", label: "PKT - Pakistan Standard Time (UTC +5)" },
  { value: "Asia/Tashkent", label: "UZT - Uzbekistan Time (UTC +5)" },
  { value: "Asia/Kolkata", label: "IST - India Standard Time (UTC +5:30)" },
  { value: "Asia/Colombo", label: "IST - Sri Lanka Standard Time (UTC +5:30)" },
  { value: "Asia/Kathmandu", label: "NPT - Nepal Time (UTC +5:45)" },
  { value: "Asia/Dhaka", label: "BST - Bangladesh Standard Time (UTC +6)" },
  { value: "Asia/Almaty", label: "ALMT - Almaty Time (UTC +6)" },
  { value: "Asia/Yangon", label: "MMT - Myanmar Time (UTC +6:30)" },
  { value: "Asia/Bangkok", label: "ICT - Indochina Time (UTC +7)" },
  { value: "Asia/Jakarta", label: "WIB - Western Indonesia Time (UTC +7)" },
  { value: "Asia/Shanghai", label: "CST - China Standard Time (UTC +8)" },
  { value: "Asia/Hong_Kong", label: "HKT - Hong Kong Time (UTC +8)" },
  { value: "Asia/Singapore", label: "SGT - Singapore Time (UTC +8)" },
  { value: "Asia/Taipei", label: "CST - Taipei Standard Time (UTC +8)" },
  { value: "Australia/Perth", label: "AWST - Australian Western Standard Time (UTC +8)" },
  { value: "Asia/Tokyo", label: "JST - Japan Standard Time (UTC +9)" },
  { value: "Asia/Seoul", label: "KST - Korea Standard Time (UTC +9)" },
  { value: "Australia/Adelaide", label: "ACST - Australian Central Standard Time (UTC +9:30)" },
  { value: "Australia/Sydney", label: "AEST - Australian Eastern Standard Time (UTC +10)" },
  { value: "Pacific/Guam", label: "ChST - Chamorro Standard Time (UTC +10)" },
  { value: "Pacific/Noumea", label: "NCT - New Caledonia Time (UTC +11)" },
  { value: "Pacific/Auckland", label: "NZST - New Zealand Standard Time (UTC +12)" },
  { value: "Pacific/Fiji", label: "FJT - Fiji Time (UTC +12)" },
  { value: "Pacific/Tongatapu", label: "TOT - Tonga Time (UTC +13)" },
];
