project_id = "iqsjhrhsjlgjiaedzmtz"

[functions.discord-notify]
verify_jwt = false

[functions.resolve-discord-id]
verify_jwt = false

[functions.scrape-knowledge]
verify_jwt = false

[functions.techfleet-chat]
verify_jwt = false
