// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Account Deletion
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["70.1", "70.2", "70.3", "AD-004"];

describe("Account Deletion" + " (smoke)", () => {
  it("70.1: Authenticated user can delete their account", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("70.1");
  });

  it("70.2: Unauthenticated request is rejected", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("70.2");
  });

  it("70.3: Deletion cascades to all related tables", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("70.3");
  });

  it("AD-004: Orphaned data cleanup on auth user deletion", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("AD-004");
  });
});
