// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Activity Log
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["53.1", "53.13", "53.2", "53.3", "53.4", "53.5", "53.6", "53.7", "53.8", "53.9"];

describe("Activity Log" + " (smoke)", () => {
  it("53.1: Activity Log visible to admins only", () => {
    expect(appSrc).toMatch("/admin/activity-log");
  });

  it("53.13: Admin RLS on audit_log", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.13");
  });

  it("53.2: Activity Log sidebar link for admins", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.2");
  });

  it("53.3: Activity Log displays date column", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.3");
  });

  it("53.4: Activity Log displays user who took action", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("53.4");
  });

  it("53.5: Activity Log displays event type with icon", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.5");
  });

  it("53.6: Activity Log displays error messages", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.6");
  });

  it("53.7: Activity Log search filtering", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("53.7");
  });

  it("53.8: Activity Log event type filter", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.8");
  });

  it("53.9: Activity Log pagination", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("53.9");
  });
});
