// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Announcement Email
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["81.1", "81.2"];

describe("Announcement Email" + " (smoke)", () => {
  it("81.1: Announcement email is sent to subscribed users", () => {
    expect(scenarioIds).toContain("81.1");
    expect("Announcement email is sent to subscribed users".length).toBeGreaterThan(0);
  });

  it("81.2: Unsubscribed users do not receive announcement emails", () => {
    expect(scenarioIds).toContain("81.2");
    expect("Unsubscribed users do not receive announcement emails".length).toBeGreaterThan(0);
  });
});
