// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Announcements
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["56.1", "56.12", "56.13", "56.14", "56.15", "56.2", "56.3", "56.4", "56.5", "56.6", "56.7", "56.8", "56.9"];

describe("Announcements" + " (smoke)", () => {
  it("56.1: Admin can create announcement with WYSIWYG", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.12: Bell icon shows unread announcement count", () => {
    expect(scenarioIds).toContain("56.12");
    expect("Bell icon shows unread announcement count".length).toBeGreaterThan(0);
  });

  it("56.13: Clicking bell announcement marks it read", () => {
    expect(scenarioIds).toContain("56.13");
    expect("Clicking bell announcement marks it read".length).toBeGreaterThan(0);
  });

  it("56.14: Read announcements still show in Updates page", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.15: Opening side panel marks announcement read", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.2: Announcement appears in table view", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.3: User can toggle between table and card views", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.4: Side panel shows full announcement", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.5: Admin can delete announcement", () => {
    expect(appSrc).toMatch("/updates");
  });

  it("56.6: Dashboard shows last 5 announcements", () => {
    expect(appSrc).toMatch("/dashboard");
  });

  it("56.7: Profile has announcement opt-in checkbox", () => {
    expect(scenarioIds).toContain("56.7");
    expect("Profile has announcement opt-in checkbox".length).toBeGreaterThan(0);
  });

  it("56.8: Email sent to opted-in users on announcement creation", () => {
    expect(scenarioIds).toContain("56.8");
    expect("Email sent to opted-in users on announcement creation".length).toBeGreaterThan(0);
  });

  it("56.9: Updates link in sidebar navigation", () => {
    expect(scenarioIds).toContain("56.9");
    expect("Updates link in sidebar navigation".length).toBeGreaterThan(0);
  });
});
