// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: App Layout
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["67.1", "67.2", "67.3", "67.4"];

describe("App Layout" + " (smoke)", () => {
  it("67.1: App layout renders sidebar and main content", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("67.1");
  });

  it("67.2: Sidebar shows correct navigation links", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("67.2");
  });

  it("67.3: Sidebar collapses on mobile", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("67.3");
  });

  it("67.4: Sidebar highlights active page", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("67.4");
  });
});
