// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Certifications
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["CERT-TITLE-002", "CERT-TITLE-003"];

describe("Certifications" + " (smoke)", () => {
  it("CERT-TITLE-002: Client-side fallback for legacy rows without display_title", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("CERT-TITLE-002");
  });

  it("CERT-TITLE-003: Airtable record IDs are never shown as titles", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("CERT-TITLE-003");
  });
});
