// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Certifications
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["CERT-TITLE-002", "CERT-TITLE-003"];

describe("Certifications" + " (smoke)", () => {
  it("CERT-TITLE-002: Client-side fallback for legacy rows without display_title", () => {
    expect(scenarioIds).toContain("CERT-TITLE-002");
    expect("Client-side fallback for legacy rows without display_title".length).toBeGreaterThan(0);
  });

  it("CERT-TITLE-003: Airtable record IDs are never shown as titles", () => {
    expect(scenarioIds).toContain("CERT-TITLE-003");
    expect("Airtable record IDs are never shown as titles".length).toBeGreaterThan(0);
  });
});
