// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Class Registration
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["10.1", "10.2", "10.3", "10.4", "10.5", "10.6", "10.7"];

describe("Class Registration" + " (smoke)", () => {
  it("10.1: Successful class registration", () => {
    expect(scenarioIds).toContain("10.1");
    expect("Successful class registration".length).toBeGreaterThan(0);
  });

  it("10.2: Unsuccessful registration due to full capacity", () => {
    expect(scenarioIds).toContain("10.2");
    expect("Unsuccessful registration due to full capacity".length).toBeGreaterThan(0);
  });

  it("10.3: Unsuccessful registration due to insufficient tier", () => {
    expect(scenarioIds).toContain("10.3");
    expect("Unsuccessful registration due to insufficient tier".length).toBeGreaterThan(0);
  });

  it("10.4: Successful class cancellation by user", () => {
    expect(scenarioIds).toContain("10.4");
    expect("Successful class cancellation by user".length).toBeGreaterThan(0);
  });

  it("10.5: Unsuccessful cancellation due to missed deadline", () => {
    expect(scenarioIds).toContain("10.5");
    expect("Unsuccessful cancellation due to missed deadline".length).toBeGreaterThan(0);
  });

  it("10.6: User joins a live class session", () => {
    expect(scenarioIds).toContain("10.6");
    expect("User joins a live class session".length).toBeGreaterThan(0);
  });

  it("10.7: User schedules one-on-one coaching session (Tier 2)", () => {
    expect(scenarioIds).toContain("10.7");
    expect("User schedules one-on-one coaching session (Tier 2)".length).toBeGreaterThan(0);
  });
});
