// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Clients Management
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["90.1", "90.2", "90.3", "90.4", "90.5"];

describe("Clients Management" + " (smoke)", () => {
  it("90.1: Admin can view all clients", () => {
    expect(appSrc).toMatch("/clients");
  });

  it("90.2: Admin can create a new client", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("90.2");
  });

  it("90.3: Admin can edit client details", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("90.3");
  });

  it("90.4: Admin can deactivate a client", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("90.4");
  });

  it("90.5: Non-admin can only see active clients", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("90.5");
  });
});
