// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Code Quality
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["REFACTOR-001"];

describe("Code Quality" + " (smoke)", () => {
  it("REFACTOR-001: HTML stripping uses shared utility instead of inline DOM creation", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("REFACTOR-001");
  });
});
