// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Community Agreement
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["60.1", "60.2"];

describe("Community Agreement" + " (smoke)", () => {
  it("60.1: Community agreement displays on first login", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("60.1");
  });

  it("60.2: Community agreement content is accessible", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("60.2");
  });
});
