// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Course Content Consistency
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["39.1", "39.10", "39.2", "39.3", "39.4", "39.5", "39.6", "39.7", "39.8", "39.9"];

describe("Course Content Consistency" + " (smoke)", () => {
  it("39.1: Sticky Fleety icon appears bottom-right", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.1");
  });

  it("39.10: Course progress bar reflects completion", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.10");
  });

  it("39.2: Clicking Fleety icon opens side panel", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.2");
  });

  it("39.3: Ask Fleety option always in search", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.3");
  });

  it("39.4: Guidance tab on Resources page", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.4");
  });

  it("39.5: Search Fleety option opens widget with query", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.5");
  });

  it("39.6: Lesson panel shows only text for text-only lessons", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.6");
  });

  it("39.7: Mark as Complete button works from panel", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.7");
  });

  it("39.8: Back and Next navigation in lesson panel", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.8");
  });

  it("39.9: Agile course lesson data has content field", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("39.9");
  });
});
