// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Course Sharing
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["52.1", "52.2", "52.3", "52.4", "52.5", "52.6", "52.7"];

describe("Course Sharing" + " (smoke)", () => {
  it("52.1: Share button visible on course page", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("52.1");
  });

  it("52.2: Share button copies URL to clipboard", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("52.2");
  });

  it("52.3: Copied state resets after 2 seconds", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("52.3");
  });

  it("52.4: Unauthenticated user redirected to login from shared link", () => {
    expect(appSrc).toMatch("/courses/discord-learning");
  });

  it("52.5: Login page preserves redirect and navigates after sign-in", () => {
    expect(appSrc).toMatch("/login");
  });

  it("52.6: Login to Register link forwards redirect param", () => {
    expect(appSrc).toMatch("/login");
  });

  it("52.7: Register to Login link forwards redirect param", () => {
    expect(appSrc).toMatch("/register");
  });
});
