// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Course Breadcrumbs
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["41.1", "41.2", "41.3"];

describe("Course Breadcrumbs" + " (smoke)", () => {
  it("41.1: Breadcrumbs show on course detail page", () => {
    expect(scenarioIds).toContain("41.1");
    expect("Breadcrumbs show on course detail page".length).toBeGreaterThan(0);
  });

  it("41.2: Breadcrumb Courses link navigates to training page", () => {
    expect(appSrc).toMatch("/training");
  });

  it("41.3: Breadcrumbs show on locked course prerequisite page", () => {
    expect(scenarioIds).toContain("41.3");
    expect("Breadcrumbs show on locked course prerequisite page".length).toBeGreaterThan(0);
  });
});
