// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Courses Route Structure
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["42.2"];

describe("Courses Route Structure" + " (smoke)", () => {
  it("42.2: Sidebar shows Courses link pointing to /courses", () => {
    expect(appSrc).toMatch("/courses");
  });
});
