// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Dashboard Preferences
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["DASH-PREF-008", "refactor_self_healing_1"];

describe("Dashboard Preferences" + " (smoke)", () => {
  it("DASH-PREF-008: Existing users with old defaults get all widgets", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("DASH-PREF-008");
  });

  it("refactor_self_healing_1: Hook guarantees arrays regardless of DB shape", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("refactor_self_healing_1");
  });
});
