// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Error Reporting
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["ERR-SUPPRESS-001", "SEC-ERR-001", "SEC-ERR-002"];

describe("Error Reporting" + " (smoke)", () => {
  it("ERR-SUPPRESS-001: Suppressed SW errors never reach audit log via reportError", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("ERR-SUPPRESS-001");
  });

  it("SEC-ERR-001: Error reporter deduplicates identical errors", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-ERR-001");
  });

  it("SEC-ERR-002: Error reporter rate limits reports per minute", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-ERR-002");
  });
});
