// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Feedback Notifications
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["82.1", "82.2"];

describe("Feedback Notifications" + " (smoke)", () => {
  it("82.1: Admins are notified when feedback is submitted", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("82.1");
  });

  it("82.2: Feedback notification includes submitter info", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("82.2");
  });
});
