// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Interview Acceptance
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["INT-ACCEPT-001", "INT-ACCEPT-002", "INT-ACCEPT-003", "INT-ACCEPT-004", "INT-ACCEPT-005", "INT-ACCEPT-006"];

describe("Interview Acceptance" + " (smoke)", () => {
  it("INT-ACCEPT-001: Applicant sees status page after being invited to interview", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("INT-ACCEPT-001");
  });

  it("INT-ACCEPT-002: Applicant can accept interview invitation", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("INT-ACCEPT-002");
  });

  it("INT-ACCEPT-003: Status page shows correct info for each applicant status", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("INT-ACCEPT-003");
  });

  it("INT-ACCEPT-004: Completed application with status update routes to status page instead of editor", () => {
    expect(appSrc).toMatch("/applications/projects/");
  });

  it("INT-ACCEPT-005: Draft applications still route to application editor", () => {
    expect(appSrc).toMatch("/project-openings/");
  });

  it("INT-ACCEPT-006: Admin sees interview_accepted as a status option", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("INT-ACCEPT-006");
  });
});
