// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Member Journey: First Steps
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["3.2", "3.3", "3.4", "3.5", "3.6"];

describe("Member Journey: First Steps" + " (smoke)", () => {
  it("3.2: User completes First Steps tasks in any order", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("3.2");
  });

  it("3.3: User attempts to access Second Steps before completing First Steps", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("3.3");
  });

  it("3.4: Onboarding class content fails to load", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("3.4");
  });

  it("3.5: Service leadership class is at full capacity", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("3.5");
  });

  it("3.6: User attempts to mark user guide as complete without engaging", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("3.6");
  });
});
