// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: New User Onboarding
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["85.1", "85.2"];

describe("New User Onboarding" + " (smoke)", () => {
  it("85.1: Profile is auto-created on user registration", () => {
    expect(scenarioIds).toContain("85.1");
    expect("Profile is auto-created on user registration".length).toBeGreaterThan(0);
  });

  it("85.2: Google OAuth metadata populates profile", () => {
    expect(scenarioIds).toContain("85.2");
    expect("Google OAuth metadata populates profile".length).toBeGreaterThan(0);
  });
});
