// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Onboarding & Account Creation
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["2.10", "2.9"];

describe("Onboarding & Account Creation" + " (smoke)", () => {
  it("2.10: User resumes abandoned onboarding", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("2.10");
  });

  it("2.9: Unsuccessful email verification due to expired link", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("2.9");
  });
});
