// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Pre-Platform: Community Call & Invitation
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["1.1", "1.2"];

describe("Pre-Platform: Community Call & Invitation" + " (smoke)", () => {
  it("1.1: Prospective member attends community call and receives platform invitation", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("1.1");
  });

  it("1.2: Prospective member receives invitation without attending a call", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("1.2");
  });
});
