// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Profile Setup Page
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["55.1", "55.2"];

describe("Profile Setup Page" + " (smoke)", () => {
  it("55.1: Timezone field present on profile setup step 1", () => {
    expect(appSrc).toMatch("/profile-setup");
  });

  it("55.2: Next button works when all step 1 fields filled", () => {
    expect(scenarioIds).toContain("55.2");
    expect("Next button works when all step 1 fields filled".length).toBeGreaterThan(0);
  });
});
