// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Project Openings Page
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["87.1", "87.2", "87.3"];

describe("Project Openings Page" + " (smoke)", () => {
  it("87.1: Project openings page lists available projects", () => {
    expect(appSrc).toMatch("/project-openings");
  });

  it("87.2: User can view project opening detail", () => {
    expect(appSrc).toMatch("/project-openings/");
  });

  it("87.3: Apply button shown only for apply_now projects", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("87.3");
  });
});
