// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Project Training Course
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["PT-1"];

describe("Project Training Course" + " (smoke)", () => {
  it("PT-1: Display project training lessons with sections", () => {
    expect(appSrc).toMatch("/courses/project-training");
  });
});
