// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Project Opening Notifications
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["83.1", "83.2", "83.3"];

describe("Project Opening Notifications" + " (smoke)", () => {
  it("83.1: Users are notified when project opens for applications", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("83.1");
  });

  it("83.2: Project opening notification includes project details", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("83.2");
  });

  it("83.3: Project opening email links to project detail page", () => {
    expect(appSrc).toMatch("/project-openings/");
  });
});
