// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Projects
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["PROJ-COORD-01", "PROJ-COORD-02", "PROJ-COORD-03"];

describe("Projects" + " (smoke)", () => {
  it("PROJ-COORD-01: Admin assigns coordinator to project", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("PROJ-COORD-01");
  });

  it("PROJ-COORD-02: Coordinator shown on project opening detail", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("PROJ-COORD-02");
  });

  it("PROJ-COORD-03: Coordinator shown on application status page", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("PROJ-COORD-03");
  });
});
