// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Project Opening Detail
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["PROJ-DETAIL-001", "PROJ-DETAIL-002", "PROJ-DETAIL-003", "PROJ-DETAIL-004", "PROJ-DETAIL-005"];

describe("Project Opening Detail" + " (smoke)", () => {
  it("PROJ-DETAIL-001: Public user can view project opening detail", () => {
    expect(appSrc).toMatch("/project-openings/");
  });

  it("PROJ-DETAIL-002: Apply CTA redirects unauthenticated users to login", () => {
    expect(scenarioIds).toContain("PROJ-DETAIL-002");
    expect("Apply CTA redirects unauthenticated users to login".length).toBeGreaterThan(0);
  });

  it("PROJ-DETAIL-003: Authenticated user can apply from detail page", () => {
    expect(scenarioIds).toContain("PROJ-DETAIL-003");
    expect("Authenticated user can apply from detail page".length).toBeGreaterThan(0);
  });

  it("PROJ-DETAIL-004: Share button copies public URL", () => {
    expect(scenarioIds).toContain("PROJ-DETAIL-004");
    expect("Share button copies public URL".length).toBeGreaterThan(0);
  });

  it("PROJ-DETAIL-005: Detail page shows milestone-derived data", () => {
    expect(scenarioIds).toContain("PROJ-DETAIL-005");
    expect("Detail page shows milestone-derived data".length).toBeGreaterThan(0);
  });
});
