// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Protected Routes
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["57.1", "57.2", "57.3", "57.4"];

describe("Protected Routes" + " (smoke)", () => {
  it("57.1: Unauthenticated user is redirected to login", () => {
    expect(appSrc).toMatch("/login");
  });

  it("57.2: Authenticated user can access protected routes", () => {
    expect(scenarioIds).toContain("57.2");
    expect("Authenticated user can access protected routes".length).toBeGreaterThan(0);
  });

  it("57.3: Profile-incomplete user sees setup dialog", () => {
    expect(scenarioIds).toContain("57.3");
    expect("Profile-incomplete user sees setup dialog".length).toBeGreaterThan(0);
  });

  it("57.4: Admin-only routes reject non-admin users", () => {
    expect(scenarioIds).toContain("57.4");
    expect("Admin-only routes reject non-admin users".length).toBeGreaterThan(0);
  });
});
