// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Quest Re-engagement Nudges
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["QUEST-NUDGE-001", "QUEST-NUDGE-002", "QUEST-NUDGE-003", "QUEST-NUDGE-004", "QUEST-NUDGE-005", "QUEST-NUDGE-006"];

describe("Quest Re-engagement Nudges" + " (smoke)", () => {
  it("QUEST-NUDGE-001: Nudge sent after 7 days of inactivity", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("QUEST-NUDGE-001");
  });

  it("QUEST-NUDGE-002: No duplicate nudges within cooldown period", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("QUEST-NUDGE-002");
  });

  it("QUEST-NUDGE-003: Email nudge sent when notifications enabled", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("QUEST-NUDGE-003");
  });

  it("QUEST-NUDGE-004: No email when notifications disabled", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("QUEST-NUDGE-004");
  });

  it("QUEST-NUDGE-005: Skip users with recent progress", () => {
    expect(edgeFunctionDirs.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("QUEST-NUDGE-005");
  });

  it("QUEST-NUDGE-006: Nudge only for active non-completed quests", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("QUEST-NUDGE-006");
  });
});
