// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: React Query Config
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["PERF-RQ-001", "PERF-RQ-002"];

describe("React Query Config" + " (smoke)", () => {
  it("PERF-RQ-001: React Query skips retry on auth errors", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("PERF-RQ-001");
  });

  it("PERF-RQ-002: React Query uses exponential backoff for retries", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("PERF-RQ-002");
  });
});
