// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Readiness Checklist
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["64.1", "64.2"];

describe("Readiness Checklist" + " (smoke)", () => {
  it("64.1: Readiness checklist shows prerequisite status", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("64.1");
  });

  it("64.2: Readiness checklist blocks action when incomplete", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("64.2");
  });
});
