// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: RLS Policies
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const servicesIndex = fs.existsSync(path.join(process.cwd(), "src", "services", "index.ts"))
  ? fs.readFileSync(path.join(process.cwd(), "src", "services", "index.ts"), "utf8")
  : "";
const edgeFunctionDirs = fs.existsSync(path.join(process.cwd(), "supabase", "functions"))
  ? fs.readdirSync(path.join(process.cwd(), "supabase", "functions"))
  : [];
const scenarioIds = ["93.1", "93.2", "93.3", "93.4", "93.5", "93.6"];

describe("RLS Policies" + " (smoke)", () => {
  it("93.1: Users can only read their own profile", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("93.1");
  });

  it("93.2: Users can only CRUD their own journey progress", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("93.2");
  });

  it("93.3: Users can only CRUD their own applications", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("93.3");
  });

  it("93.4: Admins can view all profiles", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("93.4");
  });

  it("93.5: Anon role has no access to any table", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("93.5");
  });

  it("93.6: Service role can manage email tables", () => {
    expect(servicesIndex.length).toBeGreaterThan(0);
    expect(scenarioIds).toContain("93.6");
  });
});
