// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Security – OWASP A01 Path Traversal
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["OWASP-PATH-001"];

describe("Security – OWASP A01 Path Traversal" + " (smoke)", () => {
  it("OWASP-PATH-001: hasPathTraversal detects directory escape", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("OWASP-PATH-001");
  });
});
