// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Security – OWASP A05 File Upload
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["OWASP-UPLOAD-001"];

describe("Security – OWASP A05 File Upload" + " (smoke)", () => {
  it("OWASP-UPLOAD-001: validateFileUpload rejects disallowed MIME types", () => {
    expect(scenarioIds).toContain("OWASP-UPLOAD-001");
    expect("validateFileUpload rejects disallowed MIME types".length).toBeGreaterThan(0);
  });
});
