// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Security Utilities
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["SEC-JSON-001", "SEC-SQL-001", "SEC-SSRF-001", "SEC-XSS-001", "SEC-XSS-002"];

describe("Security Utilities" + " (smoke)", () => {
  it("SEC-JSON-001: safeJsonParse strips prototype pollution keys", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-JSON-001");
  });

  it("SEC-SQL-001: hasSqlInjectionPattern detects common SQL injection", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-SQL-001");
  });

  it("SEC-SSRF-001: isSafeExternalUrl blocks internal network addresses", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-SSRF-001");
  });

  it("SEC-XSS-001: deepSanitize strips script tags from nested objects", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-XSS-001");
  });

  it("SEC-XSS-002: deepSanitize blocks prototype pollution keys", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("SEC-XSS-002");
  });
});
