// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: Top-Right Header Controls
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = ["54.1", "54.2", "54.3", "54.4"];

describe("Top-Right Header Controls" + " (smoke)", () => {
  it("54.1: Profile avatar in top-right header", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("54.1");
  });

  it("54.2: Header order is search then theme then profile", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("54.2");
  });

  it("54.3: Less space between search and theme toggle", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("54.3");
  });

  it("54.4: Profile removed from sidebar footer", () => {
    expect(appSrc.length).toBeGreaterThan(1000);
    expect(scenarioIds).toContain("54.4");
  });
});
