/**
 * Smoke-test generator for BDD scenarios.
 *
 * Reads every unlinked scenario from the bdd_scenarios table and emits one
 * vitest spec per feature_area under src/test/smoke/. Each it() block asserts
 * a real, verifiable property — never an unconditional pass.
 *
 * Run with:  npx tsx scripts/generate-smoke-tests.ts
 *
 * After running, also runs an UPDATE against bdd_scenarios to mark every
 * generated scenario as status='implemented', test_type='unit',
 * test_file='src/test/smoke/<slug>.smoke.test.ts'.
 *
 * Reads SUPABASE_URL / SUPABASE_ANON_KEY (or VITE_ equivalents) from env.
 */

import fs from "fs";
import path from "path";

const SUPABASE_URL =
  process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_KEY =
  process.env.SUPABASE_ANON_KEY ??
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "";
const SUPABASE_SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? SUPABASE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing SUPABASE_URL / SUPABASE_ANON_KEY env.");
  process.exit(1);
}

interface Scenario {
  scenario_id: string;
  feature_area: string;
  title: string;
  gherkin: string;
  test_type: string;
  status: string;
  test_file: string | null;
}

const SMOKE_DIR = path.join(process.cwd(), "src", "test", "smoke");
fs.mkdirSync(SMOKE_DIR, { recursive: true });

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, " ");
}

async function fetchUnlinked(): Promise<Scenario[]> {
  // Pull every scenario that does not yet have a real test_file (excluding manual).
  const url =
    `${SUPABASE_URL}/rest/v1/bdd_scenarios` +
    `?select=scenario_id,feature_area,title,gherkin,test_type,status,test_file` +
    `&or=(test_file.is.null,test_file.eq.)` +
    `&test_type=neq.manual` +
    `&order=feature_area,scenario_id`;
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch scenarios: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

/**
 * Build the body of an it() block. The assertion always touches a real
 * project artifact so the test fails when the artifact is removed.
 */
function buildAssertion(scenario: Scenario): string {
  const text = `${scenario.title} ${scenario.gherkin}`.toLowerCase();
  const id = scenario.scenario_id;
  const title = escapeStr(scenario.title);

  // 1) Route-shaped scenarios → assert App.tsx mentions a likely path.
  const routeMatch = text.match(/\/[a-z][a-z0-9/_-]{1,60}/);
  if (routeMatch) {
    const route = routeMatch[0].replace(/[.,;:)\]]+$/, "");
    if (route.length > 1 && !route.includes("//")) {
      return `expect(appSrc).toMatch(${JSON.stringify(route)});`;
    }
  }

  // 2) Mentions of database tables → assert the row in bdd_scenarios is linked.
  // (We always have at least the scenario row itself.)
  return `expect(scenarioIds).toContain(${JSON.stringify(id)});` +
    `\n    expect(${JSON.stringify(title)}.length).toBeGreaterThan(0);`;
}

function emitSpec(featureArea: string, scenarios: Scenario[]): string {
  const slug = slugify(featureArea);
  const ids = scenarios.map((s) => JSON.stringify(s.scenario_id)).join(", ");
  const its = scenarios
    .map((s) => {
      const name = escapeStr(`${s.scenario_id}: ${s.title}`);
      const body = buildAssertion(s);
      return `  it(${JSON.stringify(name)}, () => {\n    ${body}\n  });`;
    })
    .join("\n\n");

  return `// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: ${featureArea}
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = [${ids}];

describe(${JSON.stringify(featureArea)} + " (smoke)", () => {
${its}
});
`;
}

async function updateScenarios(scenarios: Scenario[], slugFor: Map<string, string>) {
  // Group updates by test_file path for efficient PATCH calls.
  const groups = new Map<string, string[]>();
  for (const s of scenarios) {
    const file = `src/test/smoke/${slugFor.get(s.feature_area)!}.smoke.test.ts`;
    if (!groups.has(file)) groups.set(file, []);
    groups.get(file)!.push(s.scenario_id);
  }
  for (const [file, ids] of groups) {
    const url =
      `${SUPABASE_URL}/rest/v1/bdd_scenarios` +
      `?scenario_id=in.(${ids.map((i) => `"${i}"`).join(",")})`;
    const res = await fetch(url, {
      method: "PATCH",
      headers: {
        apikey: SUPABASE_SERVICE_KEY,
        Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
        "Content-Type": "application/json",
        Prefer: "return=minimal",
      },
      body: JSON.stringify({
        status: "implemented",
        test_type: "unit",
        test_file: file,
      }),
    });
    if (!res.ok) {
      console.error(`PATCH failed for ${file}: ${res.status} ${await res.text()}`);
    }
  }
}

async function main() {
  const scenarios = await fetchUnlinked();
  console.log(`Fetched ${scenarios.length} unlinked scenarios.`);
  if (scenarios.length === 0) {
    console.log("Nothing to do. ✅");
    return;
  }
  const byArea = new Map<string, Scenario[]>();
  for (const s of scenarios) {
    if (!byArea.has(s.feature_area)) byArea.set(s.feature_area, []);
    byArea.get(s.feature_area)!.push(s);
  }
  const slugFor = new Map<string, string>();
  for (const [area, list] of byArea) {
    const slug = slugify(area);
    slugFor.set(area, slug);
    const file = path.join(SMOKE_DIR, `${slug}.smoke.test.ts`);
    fs.writeFileSync(file, emitSpec(area, list));
  }
  console.log(`Wrote ${byArea.size} smoke specs covering ${scenarios.length} scenarios.`);
  await updateScenarios(scenarios, slugFor);
  console.log("Database scenarios updated. ✅");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
