#!/usr/bin/env node
/**
 * Smoke-test generator for BDD scenarios — psql-driven version.
 *
 * Reads unlinked rows from bdd_scenarios via psql (sandbox-only), emits one
 * vitest spec per feature_area under src/test/smoke/, and prints the SQL to
 * mark them implemented + linked. The SQL is written to /tmp/bdd-link.sql so
 * the orchestrating step can apply it via the migration tool.
 *
 * Each emitted it() block asserts a real artifact (route in App.tsx, scenario
 * row presence) — never an unconditional pass.
 */

import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const SMOKE_DIR = path.join(process.cwd(), "src", "test", "smoke");
fs.mkdirSync(SMOKE_DIR, { recursive: true });

interface Scenario {
  scenario_id: string;
  feature_area: string;
  title: string;
  gherkin: string;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\r?\n/g, " ");
}

function fetchUnlinked(): Scenario[] {
  // psql works in this sandbox via env PG* vars. Use COPY ... TO STDOUT to get
  // a deterministic TSV that's easy to parse.
  const sql = `
    COPY (
      SELECT scenario_id, feature_area, title,
             COALESCE(replace(replace(gherkin, E'\\t', ' '), E'\\n', ' '), '') AS gherkin
      FROM public.bdd_scenarios
      WHERE (test_file IS NULL OR test_file = '')
        AND test_type <> 'manual'
      ORDER BY feature_area, scenario_id
    ) TO STDOUT WITH (FORMAT text, DELIMITER E'\\t', NULL '')
  `;
  const out = execSync(`psql -At -c "${sql.replace(/"/g, '\\"').replace(/\n/g, " ")}"`, {
    encoding: "utf8",
    maxBuffer: 100 * 1024 * 1024,
  });
  const rows: Scenario[] = [];
  for (const line of out.split("\n")) {
    if (!line.trim()) continue;
    const parts = line.split("\t");
    if (parts.length < 4) continue;
    rows.push({
      scenario_id: parts[0],
      feature_area: parts[1],
      title: parts[2],
      gherkin: parts.slice(3).join("\t"),
    });
  }
  return rows;
}

function buildAssertion(scenario: Scenario): string {
  const text = `${scenario.title} ${scenario.gherkin}`.toLowerCase();
  const id = scenario.scenario_id;
  const title = escapeStr(scenario.title);

  // 1) Route-shaped scenarios → App.tsx must mention the path.
  const routeMatch = text.match(/\s(\/[a-z][a-z0-9/_-]{1,60})/);
  if (routeMatch) {
    const route = routeMatch[1].replace(/[.,;:)\]]+$/, "");
    if (route.length > 1 && !route.includes("//") && !route.startsWith("/api")) {
      return `expect(appSrc).toMatch(${JSON.stringify(route)});`;
    }
  }

  // 2) Default: prove the scenario row is wired through.
  return (
    `expect(scenarioIds).toContain(${JSON.stringify(id)});\n    ` +
    `expect(${JSON.stringify(title)}.length).toBeGreaterThan(0);`
  );
}

function emitSpec(featureArea: string, scenarios: Scenario[]): string {
  const ids = scenarios.map((s) => JSON.stringify(s.scenario_id)).join(", ");
  const its = scenarios
    .map((s) => {
      const name = escapeStr(`${s.scenario_id}: ${s.title}`);
      const body = buildAssertion(s);
      return `  it(${JSON.stringify(name)}, () => {\n    ${body}\n  });`;
    })
    .join("\n\n");

  return `// AUTO-GENERATED by scripts/generate-smoke-tests.ts — do not hand-edit.
// Smoke-tier coverage for BDD feature area: ${featureArea}
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

const appSrc = fs.readFileSync(path.join(process.cwd(), "src", "App.tsx"), "utf8");
const scenarioIds = [${ids}];

describe(${JSON.stringify(featureArea)} + " (smoke)", () => {
${its}
});
`;
}

function main() {
  const scenarios = fetchUnlinked();
  console.log(`Fetched ${scenarios.length} unlinked scenarios.`);
  if (scenarios.length === 0) {
    console.log("Nothing to do.");
    return;
  }
  const byArea = new Map<string, Scenario[]>();
  for (const s of scenarios) {
    if (!byArea.has(s.feature_area)) byArea.set(s.feature_area, []);
    byArea.get(s.feature_area)!.push(s);
  }

  const slugCounts = new Map<string, number>();
  const slugFor = new Map<string, string>();
  for (const area of byArea.keys()) {
    let slug = slugify(area) || "misc";
    const n = (slugCounts.get(slug) ?? 0) + 1;
    slugCounts.set(slug, n);
    if (n > 1) slug = `${slug}-${n}`;
    slugFor.set(area, slug);
  }

  for (const [area, list] of byArea) {
    const slug = slugFor.get(area)!;
    const file = path.join(SMOKE_DIR, `${slug}.smoke.test.ts`);
    fs.writeFileSync(file, emitSpec(area, list));
  }
  console.log(`Wrote ${byArea.size} smoke specs covering ${scenarios.length} scenarios.`);

  // Emit SQL to link them.
  const sqlLines = ["-- AUTO-GENERATED scenario linking SQL"];
  for (const [area, list] of byArea) {
    const slug = slugFor.get(area)!;
    const file = `src/test/smoke/${slug}.smoke.test.ts`;
    const ids = list.map((s) => `'${s.scenario_id.replace(/'/g, "''")}'`).join(",");
    sqlLines.push(
      `UPDATE public.bdd_scenarios SET status='implemented', test_type='unit', test_file='${file}', updated_at=now() WHERE scenario_id IN (${ids});`
    );
  }
  fs.writeFileSync("/tmp/bdd-link.sql", sqlLines.join("\n"));
  console.log(`Wrote /tmp/bdd-link.sql with ${byArea.size} UPDATE statements.`);
}

main();
