-- SPF edge-map FULL COVERAGE (A4 task #25). Extends the graph from 8 mapped source types
-- (43 fields) to 20 (137 fields), so career transitions, methodologies, specializations,
-- practice-components, tools, industries, project types/phases, data-type meta, and the RACI hats
-- (Who's Responsible/Accountable/Consulted/Informed) all traverse. The SPF ingest labels
-- (methodology/specialization/project_type/career_transition/data_type/practice_component/project_phase)
-- were NOT in the connected-map enum, so their edges never resolved; add them (additive, idempotent).
-- Handbooks/READMEs are intentionally NOT here — they have no spf_entity rows and reach Fleety via KB
-- retrieval (prose channel), not the graph. Generated from _extend_edge_map.mjs (single source).
-- Apply order matters: ADD VALUE must commit before spf_rebuild_edges() uses it (separate txns).

ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'career_transition';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'data_type';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'methodology';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'practice_component';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'project_phase';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'project_type';
ALTER TYPE public.framework_entity_type ADD VALUE IF NOT EXISTS 'specialization';

INSERT INTO public.spf_edge_map (src_entity_type, spf_field, rel_type, dst_entity_type) VALUES
  ('activity', 'Required Hard Skills', 'requires_skill', 'skill'),
  ('activity', 'Associated Deliverables', 'produces', 'deliverable'),
  ('activity', 'Duty Who Owns the Activity', 'owned_by', 'duty'),
  ('activity', 'Other Duties Involved', 'related_to', 'duty'),
  ('activity', 'Who''s Responsible?', 'performed_by', 'duty'),
  ('activity', 'Who''s Accountable?', 'performed_by', 'duty'),
  ('activity', 'Who''s Consulted?', 'related_to', 'duty'),
  ('activity', 'Who''s Informed?', 'related_to', 'duty'),
  ('activity', 'Possible Tech Fleet Tools to Perform the Activity', 'uses_tool', 'tool'),
  ('activity', 'Associated Job Specializations', 'related_to', 'specialization'),
  ('activity', 'Associated Agile Methodologies', 'applies_method', 'methodology'),
  ('activity', 'Milestones', 'part_of', 'project_milestone'),
  ('activity', 'Practices', 'uses_practice', 'practice'),
  ('deliverable', 'Required Skills for the Deliverable', 'requires_skill', 'skill'),
  ('deliverable', 'Required Practices for the Deliverable', 'uses_practice', 'practice'),
  ('deliverable', 'Duty Who Owns the Deliverable', 'owned_by', 'duty'),
  ('deliverable', 'Required Activities', 'requires_activity', 'activity'),
  ('deliverable', 'Project Milestone Where It''s Delivered', 'part_of', 'project_milestone'),
  ('deliverable', 'Workshops', 'related_to', 'workshop'),
  ('deliverable', 'Company Type', 'targets_company_type', 'company_type'),
  ('workshop', 'Deliverable the Workshop Produces', 'produces', 'deliverable'),
  ('workshop', 'Practices That This Workshop Teaches', 'uses_practice', 'practice'),
  ('workshop', 'What Duty Runs This Workshop?', 'performed_by', 'duty'),
  ('workshop', 'What Milestone Does This Workshop Belong To?', 'part_of', 'project_milestone'),
  ('workshop', 'Related Workshop Skills', 'requires_skill', 'skill'),
  ('workshop', 'Related Activities', 'requires_activity', 'activity'),
  ('workshop', 'Who Takes Part', 'engages_stakeholder', 'stakeholder'),
  ('skill', 'Practices Needed to Improve In This Skill', 'uses_practice', 'practice'),
  ('skill', 'Activities Involving the Skill', 'requires_activity', 'activity'),
  ('skill', 'Duties Associated With This Skill', 'performed_by', 'duty'),
  ('skill', 'Team Functions Associated With This Skill', 'part_of', 'job_function'),
  ('skill', 'Milestones', 'part_of', 'project_milestone'),
  ('skill', 'Job Industry', 'related_to', 'job_industry'),
  ('skill', 'Other Skills Required to Perform This Skill', 'requires_skill', 'skill'),
  ('duty', 'Skills Required For the Duty', 'requires_skill', 'skill'),
  ('duty', 'Foundational Skills', 'requires_skill', 'skill'),
  ('duty', 'First Step to Learn', 'requires_skill', 'skill'),
  ('duty', 'Activities', 'requires_activity', 'activity'),
  ('duty', 'Responsible Tasks', 'requires_activity', 'activity'),
  ('duty', 'Accountable Tasks', 'requires_activity', 'activity'),
  ('duty', 'Consulted Tasks', 'related_to', 'activity'),
  ('duty', 'Informed Tasks', 'related_to', 'activity'),
  ('duty', 'Milestones', 'part_of', 'project_milestone'),
  ('duty', 'Practices', 'uses_practice', 'practice'),
  ('duty', 'Responsible Deliverables', 'produces', 'deliverable'),
  ('duty', 'Associated Team Function', 'part_of', 'job_function'),
  ('duty', 'Unique Required Tools', 'uses_tool', 'tool'),
  ('duty', 'Methodologies', 'applies_method', 'methodology'),
  ('duty', 'Workshops - What RACI Hat Owns This Workshop?', 'related_to', 'workshop'),
  ('job_function', 'Practices', 'uses_practice', 'practice'),
  ('job_function', 'Skills', 'requires_skill', 'skill'),
  ('job_function', 'Foundational Skills', 'requires_skill', 'skill'),
  ('job_function', 'Skills Required for the Role', 'requires_skill', 'skill'),
  ('job_function', 'Required Activities', 'requires_activity', 'activity'),
  ('job_function', 'Responsible Deliverables', 'produces', 'deliverable'),
  ('job_function', 'Milestones', 'part_of', 'project_milestone'),
  ('job_function', 'Associated Duties', 'related_to', 'duty'),
  ('job_function', 'Possible Specializations', 'related_to', 'specialization'),
  ('job_function', 'Project Types', 'related_to', 'project_type'),
  ('job_function', 'Required Tools', 'uses_tool', 'tool'),
  ('project_milestone', 'All Deliverables In the Milestone', 'produces', 'deliverable'),
  ('project_milestone', 'UNIQUE Skills in the Milestone', 'requires_skill', 'skill'),
  ('project_milestone', 'UNIQUE Practices', 'uses_practice', 'practice'),
  ('project_milestone', 'UNIQUE Activities', 'requires_activity', 'activity'),
  ('project_milestone', 'Activities', 'requires_activity', 'activity'),
  ('project_milestone', 'Workshops', 'related_to', 'workshop'),
  ('project_milestone', 'Should Be Done Before', 'precedes', 'project_milestone'),
  ('project_milestone', 'Should Be Done After', 'related_to', 'project_milestone'),
  ('project_milestone', 'UNIQUE Who''s Responsible?', 'performed_by', 'duty'),
  ('project_milestone', 'UNIQUE Who''s Accountable?', 'performed_by', 'duty'),
  ('project_milestone', 'UNIQUE Who''s Consulted?', 'related_to', 'duty'),
  ('project_milestone', 'UNIQUE Who''s Informed?', 'related_to', 'duty'),
  ('project_milestone', 'UNIQUE Team Functions Who Are Responsible in the Milestone', 'related_to', 'job_function'),
  ('project_milestone', 'UNIQUE Team Functions Who Are Accountable to the Milestone', 'related_to', 'job_function'),
  ('project_milestone', 'UNIQUE Team Functions Who Are Consulted', 'related_to', 'job_function'),
  ('project_milestone', 'UNIQUE Functions Who Are Informed in the Milestone', 'related_to', 'job_function'),
  ('project_milestone', 'Project Types', 'related_to', 'project_type'),
  ('project_milestone', 'Project Phases - New Milestones In This Phase', 'part_of', 'project_phase'),
  ('practice', 'Other Practices Required', 'related_to', 'practice'),
  ('practice', 'UNIQUE Duties Associated with the Practice', 'performed_by', 'duty'),
  ('practice', 'Milestones', 'part_of', 'project_milestone'),
  ('practice', 'Practice Components', 'related_to', 'practice_component'),
  ('practice', 'Skills That Require the Practice', 'teaches_skill', 'skill'),
  ('practice', 'UNIQUE Functions Involving the Practice', 'related_to', 'job_function'),
  ('practice', 'Team Functions', 'related_to', 'job_function'),
  ('practice', 'UNIQUE Activities Involving the Practice', 'requires_activity', 'activity'),
  ('practice', 'Workshops', 'related_to', 'workshop'),
  ('methodology', 'Other Agile Methods', 'related_to', 'methodology'),
  ('methodology', 'Job Roles that Use the Method', 'related_to', 'duty'),
  ('methodology', 'All Tasks Involving the Methodology', 'requires_activity', 'activity'),
  ('methodology', 'User Experience Research Tasks Involving the Methodology', 'requires_activity', 'activity'),
  ('methodology', 'User Experience Design Tasks Involving the Methodology', 'requires_activity', 'activity'),
  ('methodology', 'Product Owner Tasks Involving the Methodology', 'requires_activity', 'activity'),
  ('methodology', 'Agile Coach Tasks Involving the Methodology', 'requires_activity', 'activity'),
  ('specialization', 'Related Tech Fleet Positions', 'related_to', 'job_function'),
  ('specialization', 'Specialization Tasks', 'requires_activity', 'activity'),
  ('specialization', 'Project Types', 'related_to', 'project_type'),
  ('practice_component', 'Associated Practices', 'part_of', 'practice'),
  ('career_transition', 'Industry', 'related_to', 'job_industry'),
  ('career_transition', 'Duties in the New Field', 'related_to', 'duty'),
  ('career_transition', 'Responsible Tasks', 'requires_activity', 'activity'),
  ('career_transition', 'Accountable Tasks', 'requires_activity', 'activity'),
  ('career_transition', 'Consulted Tasks', 'related_to', 'activity'),
  ('career_transition', 'Foundational Skills to Build', 'requires_skill', 'skill'),
  ('career_transition', 'Transferable Skills From This Industry', 'requires_skill', 'skill'),
  ('career_transition', 'First Steps', 'requires_skill', 'skill'),
  ('career_transition', 'Tools to Learn', 'uses_tool', 'tool'),
  ('career_transition', 'Methodologies to Learn', 'applies_method', 'methodology'),
  ('career_transition', 'Deliverables to Learn', 'related_to', 'deliverable'),
  ('career_transition', 'Practices Needed to Succeed', 'uses_practice', 'practice'),
  ('data_type', 'Examples of Skills', 'related_to', 'skill'),
  ('data_type', 'Specializations', 'related_to', 'specialization'),
  ('data_type', 'Examples of Practices', 'related_to', 'practice'),
  ('data_type', 'Roles', 'related_to', 'duty'),
  ('data_type', 'Product Milestones', 'related_to', 'project_milestone'),
  ('data_type', 'Tools', 'related_to', 'tool'),
  ('data_type', 'Tasks', 'related_to', 'activity'),
  ('data_type', 'Deliverables', 'related_to', 'deliverable'),
  ('data_type', 'Work Type', 'related_to', 'company_type'),
  ('data_type', 'Agile Methodologies', 'related_to', 'methodology'),
  ('company_type', 'Key Project Deliverables for This Environment', 'related_to', 'deliverable'),
  ('company_type', 'Stakeholders', 'engages_stakeholder', 'stakeholder'),
  ('stakeholder', 'Relevant Company Types', 'targets_company_type', 'company_type'),
  ('stakeholder', 'Workshops', 'related_to', 'workshop'),
  ('tool', 'Common Tasks Using the Tool', 'requires_activity', 'activity'),
  ('tool', 'Roles', 'related_to', 'duty'),
  ('job_industry', 'Transferrable Technical Skills Coming From This Industry', 'requires_skill', 'skill'),
  ('job_industry', 'Transferrable Interpersonal Skills Coming From This Industry', 'requires_skill', 'skill'),
  ('project_type', 'Key Specializations Involved', 'related_to', 'specialization'),
  ('project_type', 'UNIQUE Functions', 'related_to', 'job_function'),
  ('project_type', 'UX Research Deliverables', 'related_to', 'deliverable'),
  ('project_type', 'UX Design Deliverables', 'related_to', 'deliverable'),
  ('project_type', 'Product Milestones', 'related_to', 'project_milestone'),
  ('project_phase', 'New Milestones In This Phase', 'related_to', 'project_milestone'),
  ('project_phase', 'New Deliverables In This Phase', 'related_to', 'deliverable'),
  ('project_phase', 'Continued Milestones In This Phase', 'related_to', 'project_milestone'),
  ('project_phase', 'Continued Deliverables In This Phase', 'related_to', 'deliverable')
ON CONFLICT (src_entity_type, spf_field) DO UPDATE
  SET rel_type = EXCLUDED.rel_type, dst_entity_type = EXCLUDED.dst_entity_type;

-- Rebuild (service_role; guarded to active_source='spf') + refresh neighbor MV — run these
-- OUTSIDE the DDL txn:  SELECT public.spf_rebuild_edges();  SELECT public.fw_refresh_neighbors_mv();
