
INSERT INTO public.bdd_scenarios (scenario_id, feature_area, feature_area_number, title, gherkin, status, test_type) VALUES
('WSTG-INFO-03-001', 'Security', 20, 'robots.txt disallows admin paths', 'Given the robots.txt file\nWhen a search engine crawler accesses it\nThen admin, dashboard, and authenticated paths should be disallowed', 'implemented', 'manual'),
('WSTG-INFO-05-001', 'Security', 20, 'No infrastructure IDs in HTML source', 'Given the index.html file\nWhen viewing the page source\nThen no Supabase project refs or internal IDs should be visible in preconnect links', 'implemented', 'manual'),
('WSTG-CLNT-04-001', 'Security', 20, 'Auth redirect validated against allowlist', 'Given a user completes authentication\nWhen a redirect URL is stored in sessionStorage\nThen the redirect should only execute if isSafeRedirectUrl returns true', 'implemented', 'unit'),
('WSTG-ATHZ-01-001', 'Security', 20, 'Chat endpoint requires JWT authentication', 'Given an unauthenticated request to techfleet-chat\nWhen the request has no valid Bearer token\nThen the function should return 401 Unauthorized', 'implemented', 'e2e'),
('WSTG-CONF-06-001', 'Security', 20, 'Chat endpoint rejects non-POST methods', 'Given a GET request to techfleet-chat\nWhen the server processes the request\nThen it should return 405 Method Not Allowed', 'implemented', 'manual'),
('WSTG-BUSL-05-001', 'Security', 20, 'Chat rate limiting per user', 'Given a user sends 30 chat requests in 5 minutes\nWhen they send the 31st request\nThen the function should return 429 with Retry-After header', 'implemented', 'e2e'),
('OWASP-AI-INJECT-001', 'Security', 20, 'Prompt injection detection in chat', 'Given a user sends a message containing prompt injection patterns\nWhen the chat function processes it\nThen the injection attempt should be logged and system-role messages stripped', 'implemented', 'unit'),
('OWASP-AI-OUTPUT-001', 'Security', 20, 'AI output sanitization stream', 'Given the AI returns a response containing script tags or system markers\nWhen the response streams through the sanitize transform\nThen dangerous content should be stripped before reaching the client', 'implemented', 'unit'),
('CRS-WAF-001', 'Security', 20, 'CRS attack pattern detection utility', 'Given user input containing SQL injection or XSS patterns matching CRS rules\nWhen hasCRSAttackPattern is called\nThen it should return true for malicious payloads', 'implemented', 'unit'),
('MASVS-STORAGE-001', 'Security', 20, 'Sensitive input field attributes available', 'Given a form with sensitive input fields\nWhen SENSITIVE_INPUT_ATTRS are applied\nThen autocomplete, autocorrect, and password manager attributes should be disabled', 'implemented', 'unit');
