-- BDD scenarios for Discord /support ticket creation + the folded-in hardening
-- (PR #2c). Executable coverage: src/test/smoke/discord-support-ticket.smoke.test.ts.
INSERT INTO public.bdd_scenarios
  (scenario_id, feature_area, feature_area_number, title, gherkin, status, test_type, test_file, notes)
VALUES
  ('HELP-DESK-080', 'Help Desk', 7,
   'A member can open a support ticket from Discord',
   'Feature: Discord /support\n  Scenario: a linked member runs /support\n    Given a signature-verified Discord interaction\n    When they run /support with subject + details\n    Then a Freescout ticket is created for their account',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'Routed in discord-interactions; Ed25519 verification untouched.'),
  ('HELP-DESK-081', 'Help Desk', 7,
   'The /support confirmation is private (ephemeral) to the requester',
   'Feature: Ephemeral reply\n  Scenario: /support responds\n    Then the deferred reply uses flags=64 so only the requester sees it',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'A support request is not posted publicly in the channel.'),
  ('HELP-DESK-082', 'Help Desk', 7,
   'The Freescout helper is lazy-imported so it cannot break /fleety or PING',
   'Feature: Isolation\n  Scenario: FREESCOUT_API_KEY missing\n    Then only /support is affected (dynamic import); PING + /fleety still work',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'freescout.ts throws at load; dynamic import confines the tripwire.'),
  ('HELP-DESK-083', 'Help Desk', 7,
   'Unlinked / no-email Discord users get actionable feedback',
   'Feature: Fail-closed feedback\n  Scenario: an unlinked Discord user runs /support\n    Then they are told to link their account (no silent failure)',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'Resolved via profiles.discord_user_id; unlinked/no_email statuses.'),
  ('HELP-DESK-084', 'Help Desk', 7,
   'The ticket is created for the resolved member with an owned pointer',
   'Feature: Identity + ownership\n  Scenario: /support creates a ticket\n    Then it resolves the member by discord_user_id and writes a pointer owned by their auth uid',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'Owner = auth uid so RLS + My tickets work; identity from the signed payload (no IDOR).'),
  ('HELP-DESK-085', 'Help Desk', 7,
   'The /support slash command registrar is admin-gated and pinned',
   'Feature: Command registration\n  Scenario: registering /support\n    Then only an admin can register it; the function is pinned in config + manifest',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'register-support-command mirrors register-fleety-command.'),
  ('HELP-DESK-086', 'Help Desk', 7,
   'Discord /support is rate-limited per member',
   'Feature: Abuse guard\n  Scenario: a member spams /support\n    Then after the hourly cap they are told to wait (no unbounded ticket/customer creation)',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'Parity with the web create 10/hr; uses support_rate_limits (service-role, no auth.uid()).'),
  ('HELP-DESK-087', 'Help Desk', 7,
   'Discord subject/body are sanitized (control chars / null bytes)',
   'Feature: Input validation\n  Scenario: /support with control characters\n    Then the subject drops control chars and the body drops null bytes',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'Codepoint filter, parity with the web create zod.'),
  ('HELP-DESK-088', 'Help Desk', 7,
   'Discord ticket create success/failure/rate-limit is audited',
   'Feature: Observability\n  Scenario: /support runs\n    Then support_ticket_created / _create_failed / _rate_limited are emitted and classified in the Activity Log',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'auditEdgeEvent with severity info/error/warn; EVENT_TYPE_CONFIG labels.'),
  ('HELP-DESK-089', 'Help Desk', 7,
   'Legacy support DEFINER functions are hardened to search_path = ''''',
   'Feature: Search-path hardening\n  Scenario: a support DEFINER function runs\n    Then it pins search_path to empty and fully-qualifies types (public.app_role)',
   'implemented', 'unit', 'src/test/smoke/discord-support-ticket.smoke.test.ts',
   'OWASP search-path hijack hardening; freescout_* queue RPCs already scoped to public,pgmq.')
ON CONFLICT (scenario_id) DO UPDATE SET
  title = EXCLUDED.title, gherkin = EXCLUDED.gherkin, status = EXCLUDED.status,
  test_type = EXCLUDED.test_type, test_file = EXCLUDED.test_file,
  notes = EXCLUDED.notes, updated_at = now();
