INSERT INTO public.bdd_scenarios
  (feature_area, feature_area_number, scenario_id, title, gherkin, status, test_type, test_file, notes)
VALUES
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-001',
   'iOS Safari does not auto-zoom text on landscape rotation',
   E'Feature: CSS universal browser support\n  Scenario: Landscape orientation does not auto-zoom body text\n    Given a user opens the app on iOS Safari in portrait\n    When they rotate the device to landscape\n    Then [UI] body copy renders at the same logical size as portrait\n    And  [Code] src/index.css declares html { -webkit-text-size-adjust: 100% }',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-002',
   'Tap targets do not flash blue on iOS Safari',
   E'Feature: CSS universal browser support\n  Scenario: iOS tap-highlight is suppressed in favor of focus-visible\n    Given a user on iOS Safari taps any button\n    When the tap completes\n    Then [UI] no native blue rectangle flashes around the element\n    And  [UI] :focus-visible ring still renders for keyboard users\n    And  [Code] body { -webkit-tap-highlight-color: transparent } is set globally',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-003',
   'Anchor links and keyboard tabbing clear sticky 64px headers',
   E'Feature: CSS universal browser support\n  Scenario: In-page anchor lands the heading below the sticky header\n    Given a page with a sticky 64px header\n    When the user clicks an in-page anchor or Tabs onto a focusable element near the top\n    Then [UI] the target element appears below the header, not behind it\n    And  [Code] html { scroll-padding-top: 5rem } is set globally',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-004',
   'Dynamic viewport units fall back to 100vh on browsers without dvh',
   E'Feature: CSS universal browser support\n  Scenario: iOS Safari < 15.4 receives a static-viewport fallback\n    Given a user on a browser that does not support the dvh unit\n    When a screen uses h-dvh / min-h-dvh / max-h-dvh\n    Then [UI] the layout fills the visible viewport without clipping\n    And  [Code] @supports not (height: 100dvh) supplies vh-based fallbacks',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-005',
   'Safe-area utilities exist for the iPhone notch and home indicator',
   E'Feature: CSS universal browser support\n  Scenario: Authors can opt into safe-area padding with terse utilities\n    Given a developer adds pt-safe / pb-safe / pl-safe / pr-safe to a sticky surface\n    When the page renders on an iPhone with notch + home indicator\n    Then [UI] header content sits below the notch and footer content above the home bar\n    And  [Code] src/index.css registers .pt-safe / .pb-safe / .pl-safe / .pr-safe via env(safe-area-inset-*)',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-006',
   'Codebase contains no raw 100vh / h-screen / min-h-screen',
   E'Feature: CSS universal browser support\n  Scenario: Static check forbids static-viewport units in components\n    Given a contributor adds className h-screen or min-h-screen or a 100vh literal\n    When CI runs the css-portability smoke test\n    Then [Code] the test fails and lists the offending file paths\n    And  [UI] no shipped screen clips its bottom rows when the iOS URL bar collapses',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-007',
   'Every backdrop-blur surface is guarded with supports-[backdrop-filter]:',
   E'Feature: CSS universal browser support\n  Scenario: Headers stay legible on browsers without backdrop-filter\n    Given a sticky header uses backdrop-blur\n    When the page renders on Samsung Internet <=14 / older Android WebView\n    Then [UI] the header has a solid background and text remains readable\n    And  [Code] every backdrop-blur token sits next to a supports-[backdrop-filter]: bg-* fallback',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-008',
   'shadcn modal primitives default to overscroll-contain',
   E'Feature: CSS universal browser support\n  Scenario: Scrolling inside a modal does not bubble pull-to-refresh\n    Given a Dialog / Sheet / Drawer / ScrollArea is open on iOS Safari\n    When the user scrolls past the top or bottom of the modal content\n    Then [UI] the page underneath does not scroll and pull-to-refresh does not fire\n    And  [Code] each primitive className includes overscroll-contain by default',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-009',
   'AppLayout sticky headers honor the iPhone notch',
   E'Feature: CSS universal browser support\n  Scenario: Header text never sits under the iPhone status bar\n    Given a user opens the app on an iPhone with a notch in landscape\n    When AppLayout renders any of its three sticky headers\n    Then [UI] header content sits below the safe-area inset\n    And  [Code] every sticky top-0 className in AppLayout.tsx includes pt-safe',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', ''),
  ('CSS Universal Browser Support', 1127, 'CSS-COMPAT-010',
   'Toasts and mobile nav clear the home indicator and notch',
   E'Feature: CSS universal browser support\n  Scenario: Toast viewport and mobile flow nav respect safe areas\n    Given a toast appears or the FlowMobileNav renders on an iPhone\n    When the device is in any orientation\n    Then [UI] the toast does not hide behind the home indicator and the mobile nav does not slip under the notch\n    And  [Code] toast.tsx ToastViewport carries pt-safe + pb-safe and FlowMobileNav.tsx carries pt-safe',
   'implemented', 'unit', 'src/test/smoke/css-portability.smoke.test.ts', '')
ON CONFLICT (scenario_id) DO UPDATE SET
  title = EXCLUDED.title,
  gherkin = EXCLUDED.gherkin,
  status = EXCLUDED.status,
  test_type = EXCLUDED.test_type,
  test_file = EXCLUDED.test_file,
  updated_at = now();